#!/bin/bash
bamsInput=$1
ref=$2
bamOut=$3 
noThreads=$4

cat $bamsInput| parallel --gnu -j $noThreads 'samtools view -H {} > {}.script.header.sam'

headers=$( cat $bamsInput |sed -e 's/\(.*\)/I=\1.script.header.sam/'| tr -s $'\n' ' ' )

picardMergeSamFiles  $headers O=$bamOut.header.sam VERBOSITY=WARNING QUIET=true VALIDATION_STRINGENCY=SILENT

bams=$( cat  $bamsInput | tr -s $'\n' ' ' )


samtools cat -h $bamOut.header.sam -o /dev/stdout $bams | tmap mapall -n  $noThreads  -f $ref -i bam -v -Y -u --prefix-exclude 5 -o 2  -J 25 --end-repair 15 --do-repeat-clip --context stage1 map4 2>> $bamOut.new.alignmentQC_out.txt | samtools sort -m 1000M -l1 -@12 - $bamOut

samtools index $bamOut.bam
